### PR TITLE
fixed login/sign up in application.html.erb

### PR DESCRIPTION
**Pull request by minmcknight**

### CODE REVIEW

**Comment by mattcho** [comment]
Min, I tested your work on my local machine, but it spits out this. Let's talk tomorrow.
screen shot 2015-01-28 at 9 10 30 pm

**Comment by mattcho** [comment]
I got this message when I tried to log in.

**Comment by minmcknight** [comment]
Hey, you need to create an account first and then log in with the correct
email an password and that should password. I will add an error message to
show up somehow, although it might be difficult with the new layout.

**Comment by mattcho** [comment]
I see. Got it working. I added show def in user controller so users can see the message you created when user info is saved in DB. Your work was merged into master on Github now. Thanks.

**Pull request merged**
